# Generated by Django 2.0.5 on 2018-07-17 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anioLectivoInicio', models.DateField(blank=True, null=True)),
                ('anioLectivoFin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[('PRIMERO', '1'), ('SEGUNDO', '2'), ('TERCERO', '3'), ('CUARTO', '4'), ('QUINTO', '5'), ('SEXTO', '6'), ('SEPTIMO', '7')], default=None, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default=None, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('confirmpass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupos', models.IntegerField()),
                ('codigo_alec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.AnioLectivo')),
                ('codigo_cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Curso')),
                ('codigo_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evalucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('codigo_est_cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.EstudianteCurso')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Evalucion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('confirmpass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=100)),
                ('validation', models.CharField(blank=True, choices=[('Correcto', 'Correcto'), ('Incorrecto', 'Incorrecto')], default=None, max_length=10, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='preguntas',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.TipoPregunta'),
        ),
        migrations.AddField(
            model_name='historial',
            name='codigo_pre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Preguntas'),
        ),
        migrations.AddField(
            model_name='estudiantecurso',
            name='codigo_profe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Profesor'),
        ),
    ]
